- .gitignore
- Main.elm
- Mastodon.elm
- Ports.elm
- README.md
- elm-package.json
- index.html
- package.json
- style.css
> First working prototype.

- View.elm
- style.css
Before / After comparaison (Firefox nightly)
> Fix float issue with avatars + smaller avatars

- View.elm
- style.css
TODO: parse the nodes to change urls for mentions and tags
> Display Html in statuses

- src/View.elm
I just added a link on each username for each toot.
> Added link to profile on username

- public/style.css
- src/View.elm
> Improve timeline styles.

- src/Model.elm
- src/View.elm
> Handle post visibility.

- public/style.css
- src/View.elm
Credits where they're due: http://codepen.io/oloman/pen/odnqy
> Close #20: Render spoilers appropriately.

- .travis.yml
- package.json
> Travis integration

- package.json
- public/style.css
- src/Mastodon.elm
- src/Model.elm
- src/View.elm
- src/ViewHelper.elm
Referencing https://github.com/n1k0/tooty/issues/10
> WIP: Display user account

- public/style.css
- src/Mastodon.elm
- src/Model.elm
- src/View.elm
- src/ViewHelper.elm
> Fix #23: Render user mentions in the second column.

- README.md
- elm-package.json
- package.json
- public/style.css
- src/Mastodon.elm
- src/Model.elm
- src/View.elm
- src/ViewHelper.elm
> WiP: Add status action buttons.

- elm-package.json
- public/style.css
- src/Mastodon.elm
- src/Model.elm
- src/View.elm
> Aggregate notifications.

- public/style.css
- src/Mastodon.elm
- src/View.elm
This patch improves the follow notification layout and displayed information of followers, and also fixes an issue with them not being actually aggregated.
> Better follow notifications.

- package.json
- public/style.css
- src/Model.elm
- src/View.elm
Deployed on gh-pages for easier testing.
> Fix #45: Add a media viewer.

- elm-package.json
- public/style.css
- src/View.elm
> Added date for each toot

- elm-package.json
- package.json
- src/Main.elm
- src/Mastodon.elm
- src/Model.elm
- src/Util.elm
- src/ViewHelper.elm
- tests/.gitignore
- tests/Fixtures.elm
- tests/Main.elm
- tests/NotificationTests.elm
- tests/elm-package.json
> WIP: Connect to the websocket API

- public/style.css
> Fixed hashtags displayed as a block

- src/View.elm
WiP, that's a bunch of changes for such a tiny UI detail :)
> Fix #30: Unique CW and NSFW content togglers.

- src/Model.elm
> Fix #57: Reply preserving initial status visibility.

- src/Mastodon.elm
- src/Mastodon/ApiUrl.elm
> Refactored API URL

- src/Mastodon.elm
- src/Model.elm
This also refactors WebSockets handling quite a bit. Deployed to prod.
> Handle WebSocket "delete" events.

- public/style.css
> Fixed ellipsis and loong URL (finally)

- public/style.css
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Decoder.elm
- src/Mastodon/Http.elm
- src/Mastodon/Model.elm
- src/Model.elm
- src/View.elm
- src/ViewHelper.elm
I'd like reviews from @vjousse and @nicosomb and/or @magopian.
> Fix #65: Add a thread view.

- public/style.css
- src/View.elm
> Scrollable timelines.

- src/Mastodon/ApiUrl.elm
- src/Mastodon/Http.elm
- src/Model.elm
- src/View.elm
- src/ViewHelper.elm
> Fix #26: Load account timeline.

- public/style.css
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Http.elm
- src/Model.elm
- src/View.elm
> Exclude current user from draft reply mentions.

- public/style.css
- src/Model.elm
- src/View.elm
> Fix #85 : Add a link to column headings for scrolling to top.

- src/Model.elm
This is a very naive approach, also I'm not sure with the `100` default value. Feedback?
> Slice timelines to 100 entries max.

- public/style.css
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Helper.elm
- src/Mastodon/Http.elm
- src/Model.elm
- src/View.elm
Propagating the user account everywhere in views is a pain, though I don't know of a better way :/
Deployed to prod.
> Fix #97: Allow deleting a toot.

- public/style.css
- src/Command.elm
- src/Main.elm
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Http.elm
- src/Model.elm
- src/Types.elm
- src/View.elm
- src/ViewHelper.elm
I had to refactor a shitload of stuff in order to keep my sanity, sorry for that.
> WiP: Fix #81: Account followers and followings

- public/style.css
- src/Model.elm
- src/Types.elm
- src/View.elm
- src/ViewHelper.elm
> Allow filtering notifications

- elm-package.json
- public/index.html
- public/style.css
- src/Command.elm
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Helper.elm
- src/Mastodon/Http.elm
- src/Mastodon/Model.elm
- src/Model.elm
- src/Ports.elm
- src/Types.elm
- src/View.elm
- src/ViewHelper.elm
- tests/Fixtures.elm
- tests/MastodonTest/HelperTest.elm
> Closes #44: Autocomplete usernames.

- src/Model.elm
Ref https://mamot.fr/@vjousse/1055954
> Reflect status events in thread view.

- src/View/Account.elm
- src/View/Common.elm
- src/View/Draft.elm
- src/View/Notification.elm
- src/View/Status.elm
Issue #83. 
Just a little issue: the link is available in all the width of `opacity-layer` div.
> Added link to external profile in account view

- src/View/Draft.elm
> Improve visibility selector.

- src/View/Draft.elm
@n1k0 `btn-warning` is the more contrasted color here
> More contrasted toot button

- public/index.html
- src/Command.elm
- src/Model.elm
- src/Ports.elm
- src/View/Status.elm
> Add scrollIntoView port

- elm-package.json
- src/Command.elm
- src/Mastodon/Http.elm
- src/Model.elm
- src/Types.elm
- src/View/Account.elm
- src/View/App.elm
- src/View/Common.elm
- tests/Main.elm
- tests/MastodonTest/HttpTest.elm
- tests/elm-package.json
Refs #64. This patch implements the "Load more" button for the following timelines:
- the home timeline
- the local timeline
- the global timeline
- the account timeline
Notifications will be handled in a next PR.
> Fix #64: Handle paginations.

- public/style.css
- src/Model.elm
- src/Types.elm
- src/View/Error.elm
> Fix #29: Allow clearing notifications.

- src/Model.elm
- src/Types.elm
- src/View/Draft.elm
Deployed to prod. I'd like approval from @vjousse before landing this patch.
> Fix #114: Close autocomplete menu when pressing Esc.

- src/Model.elm
Patch deployed to production. I'd love feedback from @DirtyF.
> Fix #140: Reflect status events in the notifications timeline.

- public/style.css
- src/Mastodon/WebSocket.elm
- src/Model.elm
- src/Types.elm
- src/View/Error.elm
I'd like feedback from @DirtyF.
Also a review from @vjousse and/or @nicosomb.
> Fix #141: Hide error notifications after a delay.

- README.md
- package.json
Current master:
```
$ npm run build
$ ls -la build/app.js
-rw-rw-r-- 1 niko niko 1209091 May  8 12:52 build/app.js
```
This patch:
```
$ npm run build
$ npm run optimize
$ ls -la build/app.js
-rw-rw-r-- 1 niko niko 320535 May  8 12:55 build/app.js
```
That's 320k instead of 1.2MB, so a ~75% bundle size reduction, and the app works the same it seems 🍾
> Optimize generated build.

- src/Update/WebSocket.elm
The title is long but explains it all I believe. Deployed to production.
> Update thread and account views on new websocket update event.

- public/index.html
- public/style.css
- src/Command.elm
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Decoder.elm
- src/Mastodon/Encoder.elm
- src/Mastodon/Model.elm
- src/Ports.elm
- src/Subscription.elm
- src/Types.elm
- src/Update/Draft.elm
- src/Update/Main.elm
- src/View/Draft.elm
> Fix #78: Handle media upload.

- public/style.css
- src/Command.elm
- src/Init.elm
- src/Types.elm
- src/Update/AccountInfo.elm
- src/Update/Main.elm
- src/Update/Mastodon.elm
- src/Update/Route.elm
- src/Update/Timeline.elm
- src/Update/WebSocket.elm
- src/View/Account.elm
- src/View/AccountSelector.elm
- src/View/App.elm
- src/View/Blocks.elm
- src/View/Common.elm
- src/View/Draft.elm
- src/View/Formatter.elm
- src/View/Mutes.elm
- src/View/Notification.elm
- src/View/Status.elm
- src/View/Thread.elm
- src/View/Timeline.elm
> Urlify app.

- public/style.css
- src/Command.elm
- src/Init.elm
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Decoder.elm
- src/Mastodon/Model.elm
- src/Types.elm
- src/Update/Main.elm
- src/Update/Mastodon.elm
- src/Update/Route.elm
- src/Update/Search.elm
- src/View/App.elm
- src/View/Notification.elm
- src/View/Search.elm
- src/View/Timeline.elm
Tests are failing on Travis because:
> Unfortunately, there are no elm-test 0.18.4 binaries available on your operating system and architecture.
Otherwise, works great:
> Fix #160: Add search feature.

- public/style.css
- src/Mastodon/Helper.elm
- src/Mastodon/Model.elm
- src/View/Common.elm
- src/View/Notification.elm
- src/View/Status.elm
Not sure about the design, but the functionality seems to work fine.
> Add follow date in notification aggregate

- src/Init.elm
- src/Subscription.elm
- src/Types.elm
- src/Update/Main.elm
- src/View/Draft.elm
> Fix #60: Handle posting draft with ctrl + enter.

- src/Mastodon/Decoder.elm
> Application field is now optional with Mastodon v2.8+

- src/Command.elm
- src/Mastodon/ApiUrl.elm
- src/Mastodon/Decoder.elm
- src/Mastodon/Encoder.elm
- src/Mastodon/Model.elm
- src/Types.elm
- src/Update/Draft.elm
- src/Update/Main.elm
- src/Update/Mastodon.elm
- src/View/Blocks.elm
- src/View/Common.elm
- src/View/Draft.elm
- src/View/Formatter.elm
- src/View/Mutes.elm
- src/View/Status.elm
> Add status edit feature

- public/style.css
- src/Mastodon/Decoder.elm
- src/Mastodon/Model.elm
- src/View/Status.elm
Use description of attachments as a title for images.
fix #219
> Use img instead of span for images

- src/Update/Timeline.elm
- src/View/Status.elm
fix https://github.com/n1k0/tooty/issues/192
> Fix bad count number

- src/Update/Main.elm
Try to resolve https://github.com/n1k0/tooty/issues/215
> Try to fix unwanted submit

- src/View/Status.elm
> Add link to original toot

- elm.json
> fix: date-format and elm-mastodon dependencies

- elm.json
- package-lock.json
- public/style.css
- src/Types.elm
- src/Update/Draft.elm
- src/Update/Mastodon.elm
- src/Util.elm
- src/View/Draft.elm
Fix #95 for standard and custom emojis
> feat: add autocomplete for standard emojis

- elm.json
- src/Types.elm
- src/Update/Draft.elm
- src/Update/Main.elm
- src/Update/Mastodon.elm
> feat: add custom emojis to picker

- elm.json
Related to https://github.com/vjousse/elm-mastodon-tooty/pull/12 and https://github.com/n1k0/tooty/issues/256
> chore: enhance GoToSocial compat
